### ISSUE TITLE
xml: Migrate XmlPathCoordinate to use AtlasPath 

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap-runtime#111]
The Xml module uses XmlPathCoordinate and should be migrated to the common AtlasPath handler, or an extension of the AtlasPath class that supports namespaces

**Comment by igarashitm** [comment]
Issue moved to [atlasmap/atlasmap #11](https://github.com/atlasmap/atlasmap/issues/11) via [**ZenHub**](https://www.zenhub.com/)
