### ISSUE TITLE
Get rid of syndesis connector dependencies from runtime - was: Move the runtime module to syndesis github

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap-runtime#194]
Discussed w/ Tomo and John.

Move the runtime module to the syndesis project so it can inherit and specify supported dependencies for productization

**Comment by igarashitm** [comment]
It turned out we shouldn't do this, as now we have atlasmap-app which requires spring-boot runtime. However we'll remove syndesis connector dependencies from runtime at some point, as syndesis no longer require online java inspection.

**Comment by igarashitm** [comment]
We'll need to make sure online java inspection is not required even for the user provided integration logic in syndesis before doing this.

**Comment by igarashitm** [comment]
Syndesis is now working with pre-computed inspection. #86 is required for the custom classes, but it's separated from this.
