### ISSUE TITLE
[GTKA] Add json and xml serialize+deserialize tests for 100% field coverage

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap-runtime#22]
1. Add unit tests to serialize and deserialize reference mappings to and from JSON and XML
2. Validate all fields are processed correctly

**Comment by igarashitm** [comment]
Issue moved to [atlasmap/atlasmap #15](https://github.com/atlasmap/atlasmap/issues/15) via [**ZenHub**](https://www.zenhub.com/)
