### ISSUE TITLE
Java field inspection ignores package private fields

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap-runtime#253]
https://github.com/atlasmap/atlasmap-runtime/blob/ce498616965254723428641ab5c03ed80cff4d40/atlas-java-parent/atlas-java-inspect/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java#L598-L611

**Comment by mattrpav** [comment]
@igarashitm are you sure this isn't a configuration issue?  The inspection service supports configuring a number of those behaviors.. see the "disable*Fields" settings

**Comment by igarashitm** [comment]
@mattrpav if you look at the if-else clauses it only handle PRIVATE/PROTECTED/PUBLIC and no pattern for if it doesn't have any of them. I'm actually seeing package private fields are ignored on my way fixing #234. Weird thing is that not all the fields, part of them are still handled.

**Comment by mattrpav** [comment]
Ah.. "package-private".. makes sense.. we'd need to 

1. detect at the end of detectModifiers if one of public, protected and private aren't set.
2. Update Atlas JavaField modifiers enum to include PACKAGE-PRIVATE as an option
