### ISSUE TITLE
AtlasService.converterCheck() contains incomplete code

### ISSUE THREAD

**Issue by jpav** [atlasmap/atlasmap-runtime#273]
Code near the end of the method that determines whether a response should be generated indicating a converter is needed to perform a mapping has been left incomplete.  We should determine the necessity of this code and either complete its implementation or remove it from the class.

**Comment by igarashitm** [comment]
Weird thing is that we sometimes see "converter is not available" warning in UI. I thought it came from this converterCheck. Need to investigate.

**Comment by igarashitm** [comment]
I now suspect the converterCheck is not used at all. All the converter validation results I have ever seen come from validate. Make sure UI doesn't invoke it and remove.

**Comment by igarashitm** [comment]
Issue moved to [atlasmap/atlasmap #14](https://github.com/atlasmap/atlasmap/issues/14) via [**ZenHub**](https://www.zenhub.com/)
