### ISSUE TITLE
Increate unit test coverage of atlas-core

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap-runtime#36]
- [x] DefaultAtlasCombineStrategy (100%)
- [ ] DefaultAtlasContext
- [ ] DefaultAtlasContextFactory
- [ ] DefaultAtlasConversionService (74%)
- [x] DefaultAtlasPropertyStrategy (84%)
- [x] DefaultAtlasSeparateStrategy (100%)
- [x] DefaultAtlasSession (100%)
- [x] DefaultAtlasValidationService (88%)
- [x] StringDelimiter (86%)

- [x] io.atlasmap.actions (85%)
- [x] io.atlasmap.converters (99%)
- [x] io.atlasmap.validators (70%)

**Comment by igarashitm** [comment]
Issue moved to [atlasmap/atlasmap #16](https://github.com/atlasmap/atlasmap/issues/16) via [**ZenHub**](https://www.zenhub.com/)
