### ISSUE TITLE
[Documentation] Field Actions 

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap-runtime#70]
It would be great if there was a table of all the supported field actions, their parameters and input/output types.

Field Action | Input Type | Output Type | Parameter(s) | Description
------------ | ----------- | ----------- | -------- | -------- 
Capitalize | String | String | n/a | Capitalize the first character of a string

**Comment by jpav** [comment]
I think it would be even nicer if this type of information was also available in the UI

**Comment by mattrpav** [comment]
Two approaches (maybe use both) 

1. Embed the ASCII docs documentation into atlasmap-ui

2. Add FieldAction documentation structure to the Metadata that is attached to FieldActions an returned from the MappingService to the UI

**Comment by jpav** [comment]
Fixed by PR #254
